CC = gcc -Wall -Werror -Wextra
BUILD = ../build

state_sort:
	$(CC) bible.c state_sort.c -o $(BUILD)/Quest_1
	./$(BUILD)/Quest_1

state_search:
	$(CC) bible.c state_search.c -o $(BUILD)/Quest_2
	./$(BUILD)/Quest_2

clear_state:
	$(CC) bible.c clear_state.c -o $(BUILD)/Quest_3
	./$(BUILD)/Quest_3
